In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)

rows = 500

data = {
    "date": pd.date_range(start="2020-01-01", periods=rows, freq="D"),
    "temperature": np.random.normal(25, 5, rows),
    "humidity": np.random.uniform(40, 90, rows),
    "rainfall": np.random.exponential(5, rows),
    "population_density": np.random.randint(50, 1000, rows),
    "flood_event": np.random.choice([0,1], rows),
    "disease_cases": np.random.poisson(10, rows)
}

df = pd.DataFrame(data)

df.head()

,date,temperature,humidity,rainfall,population_density,flood_event,disease_cases
0,2020-01-01,27.483571,72.295862,10.272517,229,0,4
1,2020-01-02,24.308678,68.538915,0.148418,751,0,8
2,2020-01-03,28.238443,57.804836,8.738237,456,0,7
3,2020-01-04,32.615149,89.325762,0.689820,715,1,9
4,2020-01-05,23.829233,70.288741,2.040735,245,0,15

In [3]:
df.to_csv("../data/sample_disease_climate_data.csv", index=False)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                500 non-null    datetime64[us]
 1   temperature         500 non-null    float64
 2   humidity            500 non-null    float64
 3   rainfall            500 non-null    float64
 4   population_density  500 non-null    int32
 5   flood_event         500 non-null    int64
 6   disease_cases       500 non-null    int32
dtypes: datetime64[us](1), float64(3), int32(2), int64(1)
memory usage: 23.6 KB

In [5]:
df.describe()

,date,temperature,humidity,rainfall,population_density,flood_event,disease_cases
count,500,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2020-09-06 12:00:00,25.034190,65.047511,5.049387,515.380000,0.534000,10.182000
min,2020-01-01 00:00:00,8.793663,40.231601,0.024761,56.000000,0.000000,3.000000
25%,2020-05-04 18:00:00,21.498463,51.816102,1.354945,276.750000,0.000000,8.000000
50%,2020-09-06 12:00:00,25.063986,65.215227,3.635123,512.000000,1.000000,10.000000
75%,2021-01-09 06:00:00,28.183916,77.936791,6.620150,739.750000,1.000000,12.000000
max,2021-05-14 00:00:00,44.263657,89.896706,37.208615,997.000000,1.000000,21.000000
std,NaN,4.906266,14.543620,5.164650,271.369228,0.499342,3.200838